"""empty message

Revision ID: 180f23f0c79a
Revises: b87eaf58061a
Create Date: 2019-02-15 09:31:50.624789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180f23f0c79a'
down_revision = 'b87eaf58061a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_job_experience_job_type_id_fkey', 'user_job_experience', type_='foreignkey')
    op.create_foreign_key(None, 'user_job_experience', 'job_category', ['job_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_job_experience', type_='foreignkey')
    op.create_foreign_key('user_job_experience_job_type_id_fkey', 'user_job_experience', 'job_type', ['job_type_id'], ['id'])
    # ### end Alembic commands ###
